In [46]:
import pandas as pd
import os
from pymongo import MongoClient
from dotenv import load_dotenv

In [47]:
# Nama database dan collection
db_name = 'youtube_rewind_indonesia'
collection_name = 'full_labeling_2015'

# Memuat value dari file .env
load_dotenv()

mongodb_url = os.getenv('URL_SANDY')
local_url = os.getenv('URL_LOCAL')

In [48]:
# Membuat koneksi ke MongoDB
client = MongoClient(local_url)
db = client[db_name] 
full_labeling_collection = db[collection_name]

In [49]:
labeled_data = list(full_labeling_collection.find())
df_labeled = pd.DataFrame(labeled_data)

In [50]:
# Menghitung jumlah setiap label
label_counts = df_labeled['predicted_label'].value_counts()
label_counts

predicted_label
netral     7842
positif    1901
negatif     257
Name: count, dtype: int64

In [51]:
# Menyimpan jumlah ke dalam variabel
positif_count = label_counts.get('positif', 0)
negatif_count = label_counts.get('negatif', 0)
netral_count = label_counts.get('netral', 0)

# Menampilkan hasil
print(f"Jumlah komentar positif: {positif_count}")
print(f"Jumlah komentar negatif: {negatif_count}")
print(f"Jumlah komentar netral: {netral_count}")

Jumlah komentar positif: 1901
Jumlah komentar negatif: 257
Jumlah komentar netral: 7842

In [52]:
# Membagi dataframe menjadi tiga berdasarkan nilai dari kolom 'predicted_label'
df_positif = df_labeled[df_labeled['predicted_label'] == 'positif']
df_negatif = df_labeled[df_labeled['predicted_label'] == 'negatif']
df_netral = df_labeled[df_labeled['predicted_label'] == 'netral']

In [53]:
df_positif

,_id,textOriginal,predicted_label
1,6651837620ee1df904ba499b,rewind ter the best sih nice,positif
4,6651837620ee1df904ba499e,anjir keren gilak youtubers indonesia,positif
10,6651837620ee1df904ba49a4,wow seru banget video kompak,positif
11,6651837620ee1df904ba49a5,am only one who always watching this video al ...,positif
12,6651837620ee1df904ba49a6,wow kerensnjshshsjsh aku suka banget,positif
...,...,...,...
9934,6651837620ee1df904ba7068,keren bangat tetap karya youtubers indonesia,positif
9950,6651837620ee1df904ba7078,musicnya the best,positif
9984,6651837620ee1df904ba709a,suka pesan moral kena asap sempat landa wilaya...,positif
9988,6651837620ee1df904ba709e,keren abis,positif
9994,6651837620ee1df904ba70a4,wow mantap banget youtubers,positif

In [54]:
df_negatif

,_id,textOriginal,predicted_label
3,6651837620ee1df904ba499d,andai,negatif
37,6651837620ee1df904ba49bf,di sni seblum game moba entod,negatif
50,6651837620ee1df904ba49cc,kok ga seru tapi gp lanjut,negatif
88,6651837620ee1df904ba49f2,jangan bikin tahun nanti isi artis semua,negatif
90,6651837620ee1df904ba49f4,yutub rewind gada bang yon mantap jiwa jadi ci...,negatif
...,...,...,...
9738,6651837620ee1df904ba6fa4,ko edho mana ko edho,negatif
9809,6651837620ee1df904ba6feb,cuma give away ga jelas,negatif
9913,6651837620ee1df904ba7053,kok kak edhozel ga yah kecewa deh,negatif
9925,6651837620ee1df904ba705f,ko edho mana,negatif
9930,6651837620ee1df904ba7064,edhozel reza ldp mana gk ad,negatif

In [55]:
df_netral

,_id,textOriginal,predicted_label
0,6651837620ee1df904ba499a,judul lagu menit apa si ka,netral
2,6651837620ee1df904ba499c,lagu nya apa aja yang tau,netral
5,6651837620ee1df904ba499f,harus charlie charlie pencil,netral
6,6651837620ee1df904ba49a0,sini azka jadi bocah tk sekarang udah besar bgt,netral
7,6651837620ee1df904ba49a1,lagu detik,netral
...,...,...,...
9995,6651837620ee1df904ba70a5,rachel godard mana,netral
9996,6651837620ee1df904ba70a6,kangen banget gua,netral
9997,6651837620ee1df904ba70a7,kak chandra kak laurentius beatbox nya keren b...,netral
9998,6651837620ee1df904ba70a8,we mis lord rando,netral
9999,6651837620ee1df904ba70a9,anjir jaman jamanya maen warnet ampe gk inget ...,netral