In [19]:
import pandas as pd
import os
from pymongo import MongoClient
from dotenv import load_dotenv

In [20]:
# Nama database dan collection
db_name = 'youtube_rewind_indonesia'
# collection_name = 'full_labeling_2020'
collection_name = 'labeling_2020'

# Memuat value dari file .env
load_dotenv()

mongodb_url = os.getenv('URL_SANDY')
local_url = os.getenv('URL_LOCAL')

In [21]:
# Membuat koneksi ke MongoDB
client = MongoClient(local_url)
db = client[db_name] 
full_labeling_collection = db[collection_name]

In [22]:
labeled_data = list(full_labeling_collection.find())
df_labeled = pd.DataFrame(labeled_data)

In [23]:
# Menghitung jumlah setiap label
# label_counts = df_labeled['predicted_label'].value_counts()
label_counts = df_labeled['label'].value_counts()
label_counts

label
netral     991
positif    911
negatif     98
Name: count, dtype: int64

In [24]:
# Menyimpan jumlah ke dalam variabel
positif_count = label_counts.get('positif', 0)
negatif_count = label_counts.get('negatif', 0)
netral_count = label_counts.get('netral', 0)

# Menampilkan hasil
print(f"Jumlah komentar positif: {positif_count}")
print(f"Jumlah komentar negatif: {negatif_count}")
print(f"Jumlah komentar netral: {netral_count}")

Jumlah komentar positif: 911
Jumlah komentar negatif: 98
Jumlah komentar netral: 991

In [26]:
# Membagi dataframe menjadi tiga berdasarkan nilai dari kolom 'predicted_label'
# df_positif = df_labeled[df_labeled['predicted_label'] == 'positif']
# df_negatif = df_labeled[df_labeled['predicted_label'] == 'negatif']
# df_netral = df_labeled[df_labeled['predicted_label'] == 'netral']

df_positif = df_labeled[df_labeled['label'] == 'positif']
df_negatif = df_labeled[df_labeled['label'] == 'negatif']
df_netral = df_labeled[df_labeled['label'] == 'netral']

In [27]:
df_positif

,_id,textOriginal,label
0,66519bf84bec1f5ab8644847,keren ending nya sedih,positif
2,66519bf84bec1f5ab8644849,kep it trending guys,positif
4,66519bf84bec1f5ab864484b,banget keren,positif
5,66519bf84bec1f5ab864484c,ini keren banget,positif
7,66519bf84bec1f5ab864484e,merinding nontonya awal akhir god job,positif
...,...,...,...
1987,66519bf84bec1f5ab864500a,keren sangat lucu rua sedih ada haru keren san...,positif
1989,66519bf84bec1f5ab864500c,dream come true because of work together rise ...,positif
1991,66519bf84bec1f5ab864500e,keren banget woi,positif
1994,66519bf84bec1f5ab8645011,muantul,positif
1998,66519bf84bec1f5ab8645015,keren bnget,positif

In [28]:
df_negatif

,_id,textOriginal,label
83,66519bf84bec1f5ab864489a,wah cok gc nya cok aswlah,negatif
165,66519bf84bec1f5ab86448ec,udah gila boy,negatif
170,66519bf84bec1f5ab86448f1,yang kurang tebak apa hayo,negatif
240,66519bf84bec1f5ab8644937,hu anak kecil,negatif
244,66519bf84bec1f5ab864493b,gw mau kritik kakakakak video konsep nya kayak...,negatif
...,...,...,...
1907,66519bf84bec1f5ab8644fba,kecewa yotuber sukan kagak masuktapi tetep bag...,negatif
1910,66519bf84bec1f5ab8644fbd,gilak parah,negatif
1912,66519bf84bec1f5ab8644fbf,kampret sih adegan skiny keluar pintu,negatif
1925,66519bf84bec1f5ab8644fcc,eh erikontod mana nich,negatif
1940,66519bf84bec1f5ab8644fdb,ericko lim mana oi,negatif

In [29]:
df_netral

,_id,textOriginal,label
1,66519bf84bec1f5ab8644848,komen bisa kalian baca antara ratus ribu komen...,netral
3,66519bf84bec1f5ab864484a,ngueri cok,netral
6,66519bf84bec1f5ab864484d,ga bobon santoso,netral
9,66519bf84bec1f5ab8644850,mah rekor hari udah jt viewers,netral
12,66519bf84bec1f5ab8644853,tadi liat oto gledek auto dislike terus cok mu...,netral
...,...,...,...
1993,66519bf84bec1f5ab8645010,youtube rewind terbaiksaya merinding menontonya,netral
1995,66519bf84bec1f5ab8645012,udah nonton kali sekarang nonton karna keluar ...,netral
1996,66519bf84bec1f5ab8645013,coba lesti nyi cepet dah trendingnya,netral
1997,66519bf84bec1f5ab8645014,petcah,netral
1999,66519bf84bec1f5ab8645016,kok belm trending sih,netral